import { Anek_Latin } from "next/font/google";
import "./globals.css";

const anekLatin = Anek_Latin({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${anekLatin.className} antialiased`}>{children}</body>
    </html>
  );
}
